[editor_open]
command = "nvim --server $NVIM --remote-send '<cmd>lua EditLineFromScooter(\"%file\", %line)<CR>'"

# Commands available on all screens
[keys.general]
quit = "C-c"           # Exit scooter
reset = "C-r"          # Cancel in-progress operations, reset fields to default values and return to search screen
show_help_menu = "C-h" # Show the help menu containing keymaps

# Commands available on the search screen
[keys.search]
toggle_preview_wrapping = "C-l" # Toggle wrapping of lines that don't fit within the width of the preview

# Commands available on the search screen, when the search fields are focussed
[keys.search.fields]
unlock_prepopulated_fields = "A-u" # Allow editing of fields that were populated using CLI args, such as `--search_text foo`. (Note that you can use the `disable_prepopulated_fields` config option to change the default behaviour.)
trigger_search = "enter"           # Trigger a search
focus_next_field = "tab"           # Focus on the next field
focus_previous_field = "S-tab"     # Focus on the previous field

# Commands available on the search screen, when the search results are focussed
[keys.search.results]
trigger_replacement = "enter" # Trigger a replacement
back_to_fields = ["esc", "C-o"] # Move focus back to the search fields
open_in_editor = "e" # Open the currently selected search result in your editor. The editor command can be overriden using the `editor_open` section of your config.
move_down = ["j", "down", "C-n"] # Navigate to the search result below
move_up = ["k", "up", "C-p"] # Navigate to the search result above
move_down_half_page = "C-d" # Navigate to the search result half a page below
move_up_half_page = "C-u" # Navigate to the search result half a page above
move_down_full_page = [
  "C-f",
  "pagedown",
] # Navigate to the search result a page below
move_up_full_page = [
  "C-b",
  "pageup",
] # Navigate to the search result a page above
move_top = "g" # Navigate to the first search result
move_bottom = "G" # Navigate to the last search result
toggle_selected_inclusion = "space" # Toggle whether the currently highlighted result will be replaced or ignored
toggle_all_selected = "a" # Toggle whether all results will be replaced or ignored
toggle_multiselect_mode = "v" # Toggle whether multiselect mode is enabled
flip_multiselect_direction = "A-;" # Flip the direction of the multiselect selection

# Commands available on the replacement-in-progress screen
[keys.performing_replacement]

# Commands available on the results screen
[keys.results]
scroll_errors_down = ["j", "down", "C-n"] # Navigate to the error below
scroll_errors_up = ["k", "up", "C-p"] # Navigate to the error above
quit = [
  "enter",
  "q",
] # Exit scooter. This is in addition to the `quit` command in the `general` section.
