[".asdf"]
  type = "archive"
  refreshPeriod = "168h"
  exact = true
  stripComponents = 1
  url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.9.0.tar.gz"
[".vim/autoload/plug.vim"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "24h"
[".zinit/bin"]
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/zdharma-continuum/zinit.git"
[".config/fzf/fzf-zsh-plugin"]
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/unixorn/fzf-zsh-plugin.git"
[".config/nvim/autoload/plug.vim"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "24h"
