[".asdf"]
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/asdf-vm/asdf.git"
[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".config/nvim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".zinit/bin"]
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/zdharma-continuum/zinit.git"
