[".asdf"]
url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.14.1.tar.gz"
type = "archive"
exact = true
stripComponents = 1
[".vim/autoload/plug.vim"]
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
type = "file"
exact = true
refreshPeriod = "168h"
[".config/zsh/completions/_fzf"]
url = "https://raw.githubusercontent.com/junegunn/fzf/refs/heads/master/shell/completion.zsh"
type = "file"
exact = true
refreshPeriod = "168h"
[".config/zsh/completions/_chezmoi"]
url = "https://raw.githubusercontent.com/twpayne/chezmoi/refs/heads/master/completions/chezmoi.zsh"
type = "file"
exact = true
refreshPeriod = "168h"
[".config/zsh/completions/_eza"]
url = "https://raw.githubusercontent.com/eza-community/eza/refs/heads/main/completions/zsh/_eza"
type = "file"
exact = true
refreshPeriod = "168h"
[".config/yazi/plugins/starship.yazi"]
url = "https://github.com/Rolv-Apneseth/starship.yazi.git"
type = "git-repo"
refreshPeriod = "168h"
[".local/share/eclipse/eclipse-java-google-style.xml"]
url = "https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml"
type = "file"
exact = true
[".local/share/eclipse/lombok.jar"]
url = "https://projectlombok.org/downloads/lombok.jar"
type = "file"
exact = true
[".local/share/fzf"]
url = "https://github.com/junegunn/fzf"
type = "git-repo"
refreshPeriod = "168h"
