words = [
    "ansi",
    "bufnr",
    "cmake",
    "cursorline",
    "foldtext",
    "gitcommit",
    "gitsigns",
    "gomod",
    "gopls",
    "gotmpl",
    "gowork",
    "hlgroup",
    "hlgroups",
    "keybinds",
    "keymaps",
    "linters",
    "localleader",
    "mapleader",
    "maplocalleader",
    "mise",
    "multilines",
    "namu",
    "neogit",
    "noremap",
    "nvim",
    "tmux",
    "wezterm",
    "yazi",
]
