words = [
    "ansi",
    "bufnr",
    "cmake",
    "cursorline",
    "diffview",
    "exifaudio",
    "foldtext",
    "gclu",
    "gforkd",
    "gforku",
    "gitcommit",
    "gitsigns",
    "glrd",
    "glrdcl",
    "glrdcr",
    "glrucl",
    "glrucr",
    "gludcd",
    "gludcu",
    "gomod",
    "gopls",
    "gotmpl",
    "gowork",
    "grud",
    "grudcd",
    "grudcu",
    "gver",
    "hlgroup",
    "hlgroups",
    "iina",
    "karabiner",
    "keka",
    "keybinds",
    "keymaps",
    "linters",
    "localleader",
    "loclist",
    "mapleader",
    "maplocalleader",
    "mediainfo",
    "mise",
    "multilines",
    "namu",
    "neogit",
    "neovim",
    "noremap",
    "nvim",
    "qflist",
    "rebar",
    "tmux",
    "tnc",
    "tnp",
    "tns",
    "wezterm",
    "xdg",
    "yazi",
]
