words = [
    "bufnr",
    "cursorline",
    "foldtext",
    "gitcommit",
    "gitsigns",
    "hlgroup",
    "hlgroups",
    "keymaps",
    "localleader",
    "mapleader",
    "maplocalleader",
    "mise",
    "multilines",
    "namu",
    "neogit",
    "nvim",
    "yazi",
]
