[settings]
pin = true
experimental = true
http_timeout = "30s"
idiomatic_version_file_enable_tools = []
# NOTE: deprecated
go_set_gopath = true

[tools]
elixir = "1.18.4-otp-28"
erlang = "28.0.2"
go = "1.25.1"
java = "24.0.1"
kotlin = "2.1.21"
lua = "5.4.7"
node = "24.7.0"
python = "3.12.5"
ruby = "3.4.5"
rust = "1.89.0"
zig = "0.15.1"

act = "latest"
action-validator = "latest"
actionlint = "latest"
bat = "latest"
bfs = "latest"
bottom = "latest"
bun = "latest"
ctop = "latest"
delta = "latest"
deno = "latest"
difftastic = "latest"
doggo = "latest"
dust = "latest"
dyff = "latest"
editorconfig-checker = "latest"
elixir-ls = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
glow = "latest"
hadolint = "latest"
hyperfine = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
lsd = "latest"
lua-language-server = "latest" 
neovim = "latest"
protoc = "latest"
protolint = "latest"
rebar = "latest"
ripgrep = "latest"
shellcheck = "latest"
shellspec = "latest"
sqlite = "latest"
starship = "latest"
swag = "latest"
taplo = "latest"
tmux = "latest"
trdsql = "latest"
tree-sitter = "latest"
usql = "latest"
uv = "latest"
vim = "latest"
yamlfmt = "latest"
yamllint = "latest"
yazi = "latest"
zoxide = "latest"

"aqua:docker/buildx" = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"

"cargo:broot" = "latest"
"cargo:eza" = "latest"
"cargo:navi" = "latest"
"cargo:ouch" = "latest"
"cargo:procs" = "latest"
"cargo:sd" = "latest"
"cargo:selene" = "latest"
"cargo:tealdeer" = "latest"
"cargo:xplr" = "latest"

"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/google/go-jsonnet/cmd/jsonnet" = "latest"
"go:github.com/google/go-jsonnet/cmd/jsonnet-deps" = "latest"
"go:github.com/google/go-jsonnet/cmd/jsonnet-lint" = "latest"
"go:github.com/google/go-jsonnet/cmd/jsonnetfmt" = "latest"
"go:github.com/grafana/jsonnet-language-server" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/mgechev/revive" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:github.com/noahgorstein/jqp" = "latest"
"go:github.com/segmentio/golines" = "latest"
"go:github.com/xo/usql" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:gotest.tools/gotestsum" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"
"go:sigs.k8s.io/kind" = "latest"

"npm:@fsouza/prettierd" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:biome" = "latest"
"npm:cspell" = "latest"
"npm:oxlint" = "latest"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:rustywind" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"

