[settings]
pin = true
experimental = true
http_timeout = "30s"
idiomatic_version_file_enable_tools = []
# NOTE: deprecated
go_set_gopath = true

[tools]
elixir = "1.18.4-otp-28"
erlang = "28.0.2"
go = "1.25.1"
java = "24.0.1"
kotlin = "2.1.21"
lua = "5.4.7"
node = "24.7.0"
python = "3.12.5"
ruby = "3.4.6"
rust = "1.90.0"
zig = "0.15.1"

act = "latest"
action-validator = "latest"
actionlint = "latest"
bat = "latest"
bfs = "latest"
bottom = "latest"
bun = "latest"
ctop = "latest"
delta = "latest"
deno = "latest"
difftastic = "latest"
doggo = "latest"
dust = "latest"
dyff = "latest"
editorconfig-checker = "latest"
elixir-ls = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
glow = "latest"
hadolint = "latest"
hyperfine = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
lsd = "latest"
lua-language-server = "latest"
neovim = "latest"
protoc = "latest"
protolint = "latest"
rebar = "latest"
ripgrep = "latest"
shellcheck = "latest"
shellspec = "latest"
sqlite = "latest"
starship = "latest"
swag = "latest"
taplo = "latest"
tmux = "latest"
trdsql = "latest"
tree-sitter = "latest"
usql = "latest"
uv = "latest"
vim = "latest"
yamlfmt = "latest"
yamllint = "latest"
yazi = "latest"
zoxide = "latest"

"aqua:docker/buildx" = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"

"cargo:broot" = "latest"
"cargo:codebook" = "latest"
"cargo:eza" = "latest"
"cargo:harper-ls" = "latest"
"cargo:jiq" = "latest"
"cargo:monolith" = "latest"
"cargo:navi" = "latest"
"cargo:ouch" = "latest"
"cargo:procs" = "latest"
"cargo:scooter" = "latest"
"cargo:sd" = "latest"
"cargo:selene" = "latest"
"cargo:tealdeer" = "latest"
"cargo:treemd" = "latest"
"cargo:xplr" = "latest"

"github:dlvhdr/gh-dash" = "latest"
"github:JohnnyMorganz/StyLua" = "latest"
"github:bufbuild/buf" = "latest"
"github:clangd/clangd" = "latest"
"github:docker/docker-language-server" = { version = "latest", bin = "docker-language-server" }
"github:erlang-ls/erlang_ls" = "latest"
"github:mrjosh/helm-ls" = "latest"
